{% set name = "allantools" %}
{% set version = "2024.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 81b3274c83351ee573f754a62a66ad27b4e1ca7b9b36e47674d57d48622ce5be

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - numpydoc
    - pytest-runner
    - setuptools
    - python >=3.6
    - pip
    - hatchling
  run:
    - python >=3.6
    - numpy
    - scipy

test:
  imports:
    - allantools
    - allantools.dataset
    - allantools.ci
    - allantools.noise
    - allantools.noise_kasdin
    - allantools.plot
    - allantools.realtime

about:
  home: https://github.com/aewallin/allantools
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: LICENSE.txt
  summary: 'Allan deviation and related time & frequency statistics library in Python'
  description: |
    A python library for calculating Allan deviation and related time & frequency statistics.
    LGPL v3+ license.
  doc_url: https://allantools.readthedocs.io
  dev_url: https://github.com/aewallin/allantools

extra:
  recipe-maintainers:
    - aewallin
