travis:
  secure:
    BINSTAR_TOKEN: A+Kg51TOBTd6T2EVV8Ve5RNVBnRO5eELAcEjX6icUx68qf4frEhr+uWVU6e3dnnlY9D1xMZ2g5QjB1KS5nh0u7oJHKJprBZsWTwMt6bLpuT9iUMnb3Fs7Gpcdsc07/gz+2pJFGVcKg5EqNCh0Fst/k65NzFHs6WzgbcdxRrj/+y7XREE94gZlTJNj9xGYGy79TqPcNCY4XRF0H2WoNJUJM9KKSssozbFEkYGkx8v22OBdVFDs+N+zafcsZ9yztxNu7vHO7xp7NCZfUQD2DnOzLtJ2AI1ke9ZsMYKKR61YWZ2YDTbENjcXx83gp20KVe+OBxBXd4CZWTaDzQhOstNXOWcKo5UBmVauD7qsuJCcABSk9dbOxaOJMqps93Wq+Q29741eJJQ5ab9RO5wXMAPfSEuw89nCynncwvZbxoFBJm0vI9kMZ88nqniuL5S5AHI4wfSemXcib4QSP8Ch/aKj2hnqhVCI6wyCxL0vPZgthN2cRGKFQQ9r+V+lgNrjJKrP/EbbPmTK2PZgtEueCWMD3Om1Ut63YENJl2fEqX/fscEeCkoG9FZXLXlFnZT8IvybsIpTn9VR3eLXZ6NnZJ4kELf2zlM1IVraR9w+4ysYmbyZTJZjDLcdmF5rlK668zvln4UiFOXSEAwnpMWNZP90ZrsvfvaBw6oRG5rEG6b7K4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
